import taxonomy from '../../config/game-dna-taxonomy.json' with {type:'json'};
import index from '../../data/game-dna/index.json' with {type:'json'};
import catalog from '../../data/catalog-visible.json' with {type:'json'};
const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const known=new Map((index.entries||[]).map(item=>[item.slug,item]));
const entries=(catalog||[]).filter(item=>item?.slug).map(item=>({...item,...(known.get(item.slug)||{}),status:known.get(item.slug)?.status||'missing'}));
let current=null;
function filtered(){const q=el('search').value.trim().toLowerCase(),status=el('status').value;return entries.filter(item=>(!q||[item.title,item.slug,item.game_id].some(value=>String(value||'').toLowerCase().includes(q)))&&(!status||item.status===status))}
function render(){el('summary').innerHTML=[['Всего игр',entries.length],['DNA создан',entries.filter(item=>item.status!=='missing').length],['Готово для similarity',entries.filter(item=>item.quality?.ready_for_similarity).length]].map(([label,value])=>`<article class="ig-card ig-admin-card"><div class="ig-kicker">${label}</div><h2>${value}</h2></article>`).join('');el('rows').innerHTML=filtered().map(item=>`<tr><td><strong>${esc(item.title)}</strong><br><code>${esc(item.game_id||'')}</code><br><small>${esc(item.slug)}</small></td><td>${esc(item.status)}<br><small>rev ${item.revision||0}</small></td><td>${item.quality?`${item.quality.core_axes||0}/${item.quality.total_core_axes||7} core`:'—'}</td><td>${item.updated_at?new Date(item.updated_at).toLocaleString('ru-RU'):'—'}</td><td>${item.status==='missing'?'<span class="ig-pill">DNA ещё не материализован</span>':`<button class="ig-button secondary" data-edit="${esc(item.slug)}">Редактировать DNA</button>`} <a class="ig-button secondary" href="../../game/${encodeURIComponent(item.slug)}/" target="_blank">Игра ↗</a></td></tr>`).join('')}
async function openEditor(slug){try{const module=await import(`../../data/game-dna/${slug}.json`,{with:{type:'json'}});current=structuredClone(module.default);el('editor').hidden=false;el('editorTitle').textContent=current.title;el('editorMeta').textContent=`${current.game_id} · ${current.slug} · revision ${current.revision||0}`;el('publicPage').href=`../../game/${encodeURIComponent(slug)}/`;el('editorStatus').innerHTML=(taxonomy.statuses||[]).map(value=>`<option ${value===current.status?'selected':''}>${esc(value)}</option>`).join('');const locks=new Set(current.locked_axes||[]);el('axes').innerHTML=Object.entries(taxonomy.axes||{}).map(([axis,rule])=>`<tr><td><strong>${esc(rule.label||axis)}</strong>${rule.core?' <span class="ig-pill">core</span>':''}<br><code>${axis}</code></td><td><input class="ig-input" data-axis="${axis}" value="${esc((current.profile?.[axis]||[]).join(', '))}"></td><td><input type="checkbox" data-lock="${axis}" ${locks.has(axis)?'checked':''}></td></tr>`).join('');el('notes').value=current.notes||'';el('save').hidden=true;el('rebuild').hidden=true;el('copy').textContent='Показать готовый JSON';el('editorMessage').hidden=false;el('editorMessage').textContent='Профиль редактируется независимо от страницы игры. Готовый JSON можно перенести в канонический файл Game DNA.';el('editor').scrollIntoView({behavior:'smooth',block:'start'})}catch{}}
function collect(){const dna=structuredClone(current);dna.status=el('editorStatus').value;dna.notes=el('notes').value.trim();dna.profile=dna.profile||{};for(const input of el('axes').querySelectorAll('[data-axis]'))dna.profile[input.dataset.axis]=input.value.split(',').map(value=>value.trim()).filter(Boolean);dna.locked_axes=[...el('axes').querySelectorAll('[data-lock]:checked')].map(input=>input.dataset.lock);return dna}
el('mode').textContent='Game DNA хранится отдельно от страницы игры. Профиль редактируется независимо; similarity использует материализованный DNA.';el('status').innerHTML='<option value="">Все статусы DNA</option>'+[...new Set(entries.map(item=>item.status))].sort().map(value=>`<option>${esc(value)}</option>`).join('');el('search').addEventListener('input',render);el('status').addEventListener('input',render);el('rows').addEventListener('click',event=>{const button=event.target.closest('[data-edit]');if(button)openEditor(button.dataset.edit)});el('copy').addEventListener('click',()=>{if(!current)return;el('editorMessage').hidden=false;el('editorMessage').innerHTML=`<pre style="white-space:pre-wrap">${esc(JSON.stringify(collect(),null,2))}</pre>`});el('close').addEventListener('click',()=>{el('editor').hidden=true;current=null});el('editor').hidden=true;render();
