import taxonomy from '../../config/game-dna-taxonomy.json' with {type:'json'};
import index from '../../data/game-dna/index.json' with {type:'json'};
import catalog from '../../data/catalog-visible.json' with {type:'json'};
const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const known=new Map((index.entries||[]).map(item=>[item.slug,item]));
const entries=(catalog||[]).filter(item=>item?.slug).map(item=>({...item,...(known.get(item.slug)||{}),status:known.get(item.slug)?.status||'missing'}));
function filtered(){const q=el('search').value.trim().toLowerCase(),status=el('status').value;return entries.filter(item=>(!q||[item.title,item.slug,item.game_id].some(value=>String(value||'').toLowerCase().includes(q)))&&(!status||item.status===status))}
function render(){el('summary').innerHTML=[['Всего игр',entries.length],['DNA создан',entries.filter(item=>item.status!=='missing').length],['Готово для similarity',entries.filter(item=>item.quality?.ready_for_similarity).length]].map(([label,value])=>`<article class="ig-card ig-admin-card"><div class="ig-kicker">${label}</div><h2>${value}</h2></article>`).join('');el('rows').innerHTML=filtered().map(item=>`<tr><td><strong>${esc(item.title)}</strong><br><code>${esc(item.game_id||'')}</code><br><small>${esc(item.slug)}</small></td><td>${esc(item.status)}<br><small>rev ${item.revision||0}</small></td><td>${item.quality?`${item.quality.core_axes||0}/${item.quality.total_core_axes||7} core`:'—'}</td><td>${item.updated_at?new Date(item.updated_at).toLocaleString('ru-RU'):'—'}</td><td><a class="ig-button secondary" href="../../data/game-dna/${encodeURIComponent(item.slug)}.json" target="_blank">Открыть DNA</a> <a class="ig-button secondary" href="../../game/${encodeURIComponent(item.slug)}/" target="_blank">Игра ↗</a></td></tr>`).join('')}
el('mode').textContent='Game DNA хранится отдельно от страницы игры. Изменение DNA и пересчёт similarity не требуют изменения страницы.';el('status').innerHTML='<option value="">Все статусы DNA</option>'+[...new Set(entries.map(item=>item.status))].sort().map(value=>`<option>${esc(value)}</option>`).join('');el('search').addEventListener('input',render);el('status').addEventListener('input',render);el('editor').hidden=true;render();
