(function(){
'use strict';
var body=document.body;
var slug=body.getAttribute('data-article')||'';
var base='/Igropoisk';
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function getJSON(url){return fetch(url,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(r.status+' '+url);return r.json();});}
function imagesFor(section){if(section.images&&section.images.length)return section.images;if(section.image)return[section.image];return[];}
function card(section){var images=imagesFor(section);if(!images.length)return'';var slides=images.map(function(img){return '<div class="article-shot-card__slide"><img src="'+esc(img.url)+'" alt="'+esc(img.alt||img.caption||'Скриншот игры')+'" loading="lazy"></div>';}).join('');var controls=images.length>1?'<button class="article-shot-card__arrow prev" type="button">‹</button><button class="article-shot-card__arrow next" type="button">›</button><div class="article-shot-card__counter"><span>1</span> / '+images.length+'</div>':'';return '<figure class="article-shot-card" data-card="'+esc(section.id)+'"><div class="article-shot-card__viewport"><div class="article-shot-card__track">'+slides+'</div>'+controls+'</div><figcaption><div class="article-shot-card__caption">'+esc(images[0].caption||'')+'</div><div class="article-shot-card__footer"><div class="article-shot-card__dots">'+images.map(function(_,i){return '<button type="button" data-index="'+i+'" class="'+(i===0?'active':'')+'"></button>';}).join('')+'</div><a class="article-shot-card__source" href="'+esc(images[0].source_url||'#')+'" target="_blank" rel="noopener">'+esc(images[0].source_name||'Источник')+' ↗</a></div></figcaption></figure>';}
function sectionHTML(section){var ps=section.paragraphs||[];var mid=Math.max(1,Math.floor(ps.length/2));return '<section class="article-section" id="'+esc(section.id)+'"><h2>'+esc(section.heading)+'</h2>'+ps.map(function(p,i){return(i===mid?card(section):'')+'<p>'+esc(p)+'</p>';}).join('')+(ps.length<=mid?card(section):'')+'</section>';}
function render(article){var sections=article.sections||[];var sourceCount=(article.sources||[]).length;var imageCount=sections.reduce(function(n,s){return n+imagesFor(s).length;},0);body.innerHTML='<header class="article-header"><div class="ig-container article-header__inner"><a class="article-logo" href="'+base+'/">ИГРОПОИСК</a><nav class="article-nav"><a href="'+base+'/">Главное</a><a class="article-nav__game" href="'+base+'/game/'+encodeURIComponent(article.game_slug)+'/">← К игре</a></nav></div></header><section class="article-hero" style="background-image:url(&quot;'+esc(article.hero||'')+'&quot;)"><div class="ig-container article-hero__inner"><div class="article-hero__copy"><div class="article-kicker">Обзор Игропоиска</div><h1>'+esc(article.title)+'</h1><div class="article-dek">'+esc(article.dek)+'</div><div class="article-meta"><span>'+esc(article.author)+'</span><span>'+esc(article.reading_time_minutes)+' мин</span><span>'+sourceCount+' источников</span><strong class="article-score">'+esc(article.score)+' / 10</strong></div></div></div></section><main class="ig-container article-layout"><a class="article-game-return" href="'+base+'/game/'+encodeURIComponent(article.game_slug)+'/"><span>←</span><div><small>Страница игры</small><b>Открыть карточку игры</b></div></a><article class="article-body"><section class="article-quality"><div><strong>'+sourceCount+'</strong><span>источников</span></div><div><strong>'+imageCount+'</strong><span>кадров</span></div><div><strong>'+esc(article.reading_time_minutes)+'</strong><span>минут чтения</span></div></section><p class="article-lead">'+esc(article.lead)+'</p>'+sections.map(sectionHTML).join('')+'<section class="article-verdict"><div class="article-kicker">Вердикт</div><h2>'+esc(article.score)+' / 10</h2><p>'+esc(article.verdict&&article.verdict.summary||'')+'</p></section><section class="article-sources"><div class="article-sources__head"><div class="article-kicker">Источники</div><h2>Материалы, использованные при написании</h2></div><div class="article-sources__list">'+(article.sources||[]).map(function(s,i){return '<a class="article-source-row" href="'+esc(s.url)+'" target="_blank" rel="noopener"><span>'+String(i+1).padStart(2,'0')+'</span><div><b>'+esc(s.name)+'</b><small>'+esc(s.purpose||'')+'</small></div><strong>↗</strong></a>';}).join('')+'</div></section><a class="article-game-return" href="'+base+'/game/'+encodeURIComponent(article.game_slug)+'/"><span>←</span><div><small>Страница игры</small><b>Вернуться к игре</b></div></a></article></main>';install(article);}
function install(article){var map={};(article.sections||[]).forEach(function(s){map[s.id]=imagesFor(s);});document.querySelectorAll('[data-card]').forEach(function(cardEl){var images=map[cardEl.getAttribute('data-card')]||[];if(images.length<2)return;var index=0,track=cardEl.querySelector('.article-shot-card__track'),caption=cardEl.querySelector('.article-shot-card__caption'),source=cardEl.querySelector('.article-shot-card__source'),counter=cardEl.querySelector('.article-shot-card__counter span'),dots=cardEl.querySelectorAll('.article-shot-card__dots button');function show(n){index=(n+images.length)%images.length;track.style.transform='translateX(-'+index*100+'%)';caption.textContent=images[index].caption||'';source.href=images[index].source_url||'#';source.textContent=(images[index].source_name||'Источник')+' ↗';counter.textContent=String(index+1);for(var i=0;i<dots.length;i++)dots[i].classList.toggle('active',i===index);}cardEl.querySelector('.prev').onclick=function(){show(index-1);};cardEl.querySelector('.next').onclick=function(){show(index+1);};for(var i=0;i<dots.length;i++)(function(n){dots[n].onclick=function(){show(n);};})(i);});}
Promise.all([getJSON(base+'/data/articles/'+encodeURIComponent(slug)+'.json'),getJSON(base+'/data/article-media/'+encodeURIComponent(slug)+'.json').catch(function(){return null;})]).then(function(result){var article=result[0],media=result[1];if(media&&media.sections){var map={};media.sections.forEach(function(s){map[s.id]=s.images||[];});article.sections=(article.sections||[]).map(function(s){if(map[s.id])s.images=map[s.id];return s;});}render(article);}).catch(function(error){var box=document.getElementById('articleBootstrap');if(box){box.innerHTML='<a href="'+base+'/game/'+encodeURIComponent(slug)+'/">← К странице игры</a><h1>Обзор временно не загрузился</h1><p>'+esc(error.message)+'</p>';}else{body.innerHTML='<main class="ig-container" style="padding:60px 0"><h1>Обзор временно не загрузился</h1><p>'+esc(error.message)+'</p></main>';}});
})();
