(()=>{
'use strict';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const slug=document.body.dataset.article||'';
const root=document.documentElement;
const fetchJSON=async url=>{const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${response.status}: ${url}`);return response.json()};
function figure(image){return image?`<figure class="article-figure"><img src="${esc(image.url)}" alt="${esc(image.alt||image.caption||'Иллюстрация')}" loading="lazy"><figcaption><span>${esc(image.caption||'')}</span><a href="${esc(image.source_url)}" target="_blank" rel="noopener noreferrer">${esc(image.source_name||'Источник')} ↗</a></figcaption></figure>`:''}
function section(section){const paragraphs=section.paragraphs||[];return `<section class="article-section"><h2>${esc(section.heading)}</h2>${paragraphs.map((p,i)=>`${i===1?figure(section.image):''}<p>${esc(p)}</p>`).join('')}${paragraphs.length<2?figure(section.image):''}</section>`}
function sources(items){return `<section class="article-sources"><div class="article-sources__head"><div class="article-kicker">Источники</div><h2>Источники, использованные в публикации</h2></div><div class="article-sources__list">${(items||[]).map((item,index)=>`<a class="article-source-row" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer"><span>${String(index+1).padStart(2,'0')}</span><div><b>${esc(item.name)}</b><small>${esc(item.purpose||'')}</small></div><strong>↗</strong></a>`).join('')}</div></section>`}
function render(article){document.title=`${article.title} — Игропоиск`;document.body.classList.add('news-article');document.body.innerHTML=`<header class="article-header"><div class="ig-container article-header__inner"><a class="article-logo" href="../../index.html">ИГРОПОИСК</a><nav class="article-nav"><a href="../../index.html#news">Новости</a><a href="../../game/${encodeURIComponent(article.game_slug)}/">Страница игры</a></nav><button class="ig-button" id="theme" type="button" style="margin-left:auto">☀</button></div></header><section class="article-hero" id="articleHero"><div class="ig-container article-hero__inner"><div class="article-hero__copy"><div class="article-kicker">Новость</div><h1>${esc(article.title)}</h1><div class="article-dek">${esc(article.dek)}</div><div class="article-meta"><span>${esc(article.author)}</span><span>${esc(article.published_at)}</span><span class="news-source-badge">Проверено по источникам</span></div></div></div></section><main class="ig-container article-layout"><article class="article-body"><p class="article-lead">${esc(article.lead)}</p>${(article.sections||[]).map(section).join('')}${sources(article.sources)}</article></main>`;document.querySelector('#articleHero').style.backgroundImage=`url("${String(article.hero||'').replace(/"/g,'%22')}")`;const theme=document.querySelector('#theme');root.dataset.theme=localStorage.getItem('igroTheme')||root.dataset.theme||'dark';const paint=()=>theme.textContent=root.dataset.theme==='light'?'☾':'☀';paint();theme.onclick=()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';localStorage.setItem('igroTheme',root.dataset.theme);paint()}}
fetchJSON(`../../data/news-articles/${slug}.json`).then(render).catch(error=>{document.body.innerHTML=`<main class="ig-container" style="padding:60px 0"><h1>Новость не найдена</h1><p class="ig-muted">${esc(error.message)}</p></main>`})
})();
