(()=>{
  document.body.innerHTML=`
<header class="header"><a class="logo" href="../../index.html">ИГРОПОИСК</a><nav class="nav"><a href="../../index.html">Главное</a><a href="../../index.html#search">Поиск игр</a><a href="../../index.html#news">Новости</a><a href="#" aria-current="page">Игра</a></nav><div class="actions"><a class="btn" href="../../index.html#search" aria-label="Поиск игр">⌕</a><button class="btn" id="theme" aria-label="Переключить тему">☀</button></div></header>
<section class="hero"><div class="wrap"><div class="crumbs">Главное / Игры / <span id="crumb"></span></div><div class="copy"><div class="eyebrow">Страница игры</div><h1 class="title" id="title"></h1><div class="meta" id="meta"></div><p class="lead" id="lead"></p></div><aside class="scorebox" aria-label="Рейтинги игры"><div class="score-grid"><div class="score-unit"><small>Игропоиск</small><strong id="score">—</strong><span id="scoreNote"></span></div><div class="score-unit"><small>Игроки</small><strong id="userScore">—</strong><span id="userScoreNote"></span></div></div><button class="favorite" id="favorite" type="button" aria-pressed="false">♡ В избранное</button></aside><div class="thumbs" id="thumbs" aria-label="Медиа игры"></div></div></section>
<main class="wrap"><div class="tabs" role="tablist"><button class="active" data-tab="overview" role="tab">Всё об игре</button><button data-tab="media" role="tab">Медиа</button><button data-tab="reviews" role="tab">Обзоры</button><button data-tab="guides" role="tab">Гайды</button><button data-tab="sourcesTab" role="tab">Источники <span id="sourceCount"></span></button></div><section class="tab active" id="overview"><div class="grid"><article class="panel"><h2>Об игре</h2><p id="description"></p><div class="tags" id="tags"></div></article><aside class="panel"><h2>Информация</h2><dl class="details" id="details"></dl></aside></div></section><section class="tab" id="media"><div class="panel tab-panel"><h2>Медиа</h2><div class="gallery" id="gallery"></div></div></section><section class="tab" id="reviews"><div class="panel tab-panel"><h2>Обзоры</h2><div class="empty">Редакционные обзоры появятся после проверки материалов.</div></div></section><section class="tab" id="guides"><div class="panel tab-panel"><h2>Гайды</h2><div class="empty">Гайды и полезные советы находятся в подготовке.</div></div></section><section class="tab" id="sourcesTab"><div class="panel tab-panel"><h2>Источники</h2><div id="sources"></div></div></section></main>
<footer class="footer"><div class="wrap">Игропоиск</div></footer>`;
  const script=document.createElement('script');
  script.src='../_shared/game-page.js';
  document.body.appendChild(script);
})();
