(()=>{
  const script=document.createElement('script');
  script.src='../_shared/game-page-v3-bootstrap.js?v=20260812-2';
  document.head.appendChild(script);
  const qualityStyle=document.createElement('link');
  qualityStyle.rel='stylesheet';
  qualityStyle.href='../_shared/game-page-quality.css?v=20260812-1';
  document.head.appendChild(qualityStyle);
  const quality=document.createElement('script');
  quality.src='../_shared/game-page-quality.js?v=20260812-2';
  quality.defer=true;
  document.head.appendChild(quality);
  const similarity=document.createElement('script');
  similarity.src='../_shared/game-page-similarity.js?v=20260812-1';
  similarity.defer=true;
  document.head.appendChild(similarity);
  const editions=document.createElement('script');
  editions.src='../_shared/game-editions.js?v=20260807-1';
  document.head.appendChild(editions);
  const mediaCategories=document.createElement('script');
  mediaCategories.src='../_shared/game-media-categories.js?v=20260808-1';
  document.head.appendChild(mediaCategories);
  const mediaRecovery=document.createElement('script');
  mediaRecovery.src='../_shared/game-media-recovery.js?v=20260810-1';
  document.head.appendChild(mediaRecovery);
})();
